// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: EdusatUI

#ifndef _EDUSATUI_UI_H
#define _EDUSATUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Navbar;
extern lv_obj_t * ui_CompanyPanel;
extern lv_obj_t * ui_CompanyLogo;
extern lv_obj_t * ui_EdusatLabel;
extern lv_obj_t * ui_EdusatLabelText;
extern lv_obj_t * ui_NavPanel;
extern lv_obj_t * ui_TabView;
extern lv_obj_t * ui_OverviewTab;
extern lv_obj_t * ui_OverviewTopRowCont;
extern lv_obj_t * ui_BMECont;
extern lv_obj_t * ui_BMEHeaderCont;
extern lv_obj_t * ui_BMEHeaderLabel;
extern lv_obj_t * ui_BMEInfoCont;
extern lv_obj_t * ui_AltitudeInfoCont;
extern lv_obj_t * ui_AltitudeValueLabel;
extern lv_obj_t * ui_AltitudeUnitLabel;
extern lv_obj_t * ui_PressureInfoCont;
extern lv_obj_t * ui_PressureValueLabel;
extern lv_obj_t * ui_PressureUnitLabel;
extern lv_obj_t * ui_TempCont;
extern lv_obj_t * ui_TempHeaderCont;
extern lv_obj_t * ui_TempHeaderLabel;
extern lv_obj_t * ui_TempInfoCont;
extern lv_obj_t * ui_TempArc;
extern lv_obj_t * ui_TempValueLabel;
extern lv_obj_t * ui_TempUnitLabel;
extern lv_obj_t * ui_HumidityCont;
extern lv_obj_t * ui_HumidityHeaderCont;
extern lv_obj_t * ui_HumidityHeaderLabel;
extern lv_obj_t * ui_HumidityInfoCont;
extern lv_obj_t * ui_HumidtyArc;
extern lv_obj_t * ui_HumidityValueLabel;
extern lv_obj_t * ui_HumidityUnitLabel;
extern lv_obj_t * ui_MagnetometerCont;
extern lv_obj_t * ui_MagentometerHeaderCont;
extern lv_obj_t * ui_MagnetometerHeaderLabel;
extern lv_obj_t * ui_MagentometerInfoCont;
extern lv_obj_t * ui_MagentometerArc;
extern lv_obj_t * ui_MagnetometerValueLabel;
extern lv_obj_t * ui_MagentometerUnitLabel;
extern lv_obj_t * ui_OverviewBottomRowCont;
extern lv_obj_t * ui_DoubleDataCont;
extern lv_obj_t * ui_GPSCont;
extern lv_obj_t * ui_GPSHeaderCont;
extern lv_obj_t * ui_GPSHeaderLabel;
extern lv_obj_t * ui_GPSInfoCont;
extern lv_obj_t * ui_LatInfoCont;
extern lv_obj_t * ui_LatitudeValueLabel;
extern lv_obj_t * ui_LatitudeUnitLabel;
extern lv_obj_t * ui_LongInfoCont;
extern lv_obj_t * ui_LongValueLabel;
extern lv_obj_t * ui_LongUnitLabel;
extern lv_obj_t * ui_UVCont;
extern lv_obj_t * ui_UVHeaderCont;
extern lv_obj_t * ui_UVHeaderLabel;
extern lv_obj_t * ui_UVInfoCont;
extern lv_obj_t * ui_LatInfoCont1;
extern lv_obj_t * ui_UVValueLabel;
extern lv_obj_t * ui_UVUnitLabel;
extern lv_obj_t * ui_VoltageCont;
extern lv_obj_t * ui_VoltageHeaderCont;
extern lv_obj_t * ui_VoltageHeaderLabel;
extern lv_obj_t * ui_VoltageInfoCont;
extern lv_obj_t * ui_VoltageArc;
extern lv_obj_t * ui_VoltageValueLabel;
extern lv_obj_t * ui_VoltageUnitLabel;
extern lv_obj_t * ui_CurrentCont;
extern lv_obj_t * ui_CurrentHeaderCont;
extern lv_obj_t * ui_CurrentHeaderLabel;
extern lv_obj_t * ui_CurrentInfoCont;
extern lv_obj_t * ui_CurrentArc;
extern lv_obj_t * ui_CurrentValueLabel;
extern lv_obj_t * ui_CurrentUnitLabel;
extern lv_obj_t * ui_MPU6050Cont;
extern lv_obj_t * ui_MPU605HeaderCont;
extern lv_obj_t * ui_Attitude;
extern lv_obj_t * ui_MPU6050InfoCont;
extern lv_obj_t * ui_AccInfoCont;
extern lv_obj_t * ui_AltitudeValueLabel1;
extern lv_obj_t * ui_AltitudeUnitLabel1;
extern lv_obj_t * ui_GyroInfoCont;
extern lv_obj_t * ui_PressureValueLabel1;
extern lv_obj_t * ui_PressureUnitLabel1;
extern lv_obj_t * ui_SerialSelector;
extern lv_obj_t * ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
