// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: EdusatUI

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xD7D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Navbar = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Navbar, lv_pct(25));
    lv_obj_set_height(ui_Navbar, lv_pct(100));
    lv_obj_set_align(ui_Navbar, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Navbar, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Navbar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Navbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Navbar, lv_color_hex(0xE9E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Navbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompanyPanel = lv_obj_create(ui_Navbar);
    lv_obj_set_width(ui_CompanyPanel, lv_pct(100));
    lv_obj_set_height(ui_CompanyPanel, lv_pct(30));
    lv_obj_set_x(ui_CompanyPanel, -50);
    lv_obj_set_y(ui_CompanyPanel, -223);
    lv_obj_set_align(ui_CompanyPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CompanyPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CompanyPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CompanyPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CompanyLogo = lv_obj_create(ui_CompanyPanel);
    lv_obj_set_width(ui_CompanyLogo, 50);
    lv_obj_set_height(ui_CompanyLogo, 50);
    lv_obj_set_align(ui_CompanyLogo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CompanyLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CompanyLogo, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompanyLogo, lv_color_hex(0xEFEAEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompanyLogo, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CompanyLogo, lv_color_hex(0xF1EDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CompanyLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_CompanyLogo, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_CompanyLogo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_CompanyLogo, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_CompanyLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EdusatLabel = lv_obj_create(ui_CompanyPanel);
    lv_obj_set_width(ui_EdusatLabel, 100);
    lv_obj_set_height(ui_EdusatLabel, 30);
    lv_obj_set_align(ui_EdusatLabel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EdusatLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_EdusatLabel, lv_color_hex(0xF1EEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EdusatLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_EdusatLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_EdusatLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_EdusatLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_EdusatLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EdusatLabelText = lv_label_create(ui_EdusatLabel);
    lv_obj_set_width(ui_EdusatLabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EdusatLabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EdusatLabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EdusatLabelText, "EDUSAT");

    ui_NavPanel = lv_obj_create(ui_Navbar);
    lv_obj_set_width(ui_NavPanel, lv_pct(100));
    lv_obj_set_height(ui_NavPanel, lv_pct(70));
    lv_obj_set_align(ui_NavPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NavPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView, lv_pct(75));
    lv_obj_set_height(ui_TabView, lv_pct(100));
    lv_obj_set_x(ui_TabView, 99);
    lv_obj_set_y(ui_TabView, -4);
    lv_obj_set_align(ui_TabView, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_TabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_OverviewTab = lv_tabview_add_tab(ui_TabView, "Overview");
    lv_obj_set_flex_flow(ui_OverviewTab, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_OverviewTab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_border_side(ui_OverviewTab, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OverviewTab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OverviewTab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OverviewTab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OverviewTab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_OverviewTab, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OverviewTab, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OverviewTab, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OverviewTab, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_OverviewTopRowCont = lv_obj_create(ui_OverviewTab);
    lv_obj_set_width(ui_OverviewTopRowCont, lv_pct(100));
    lv_obj_set_height(ui_OverviewTopRowCont, lv_pct(49));
    lv_obj_set_align(ui_OverviewTopRowCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_OverviewTopRowCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_OverviewTopRowCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_OverviewTopRowCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_OverviewTopRowCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OverviewTopRowCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OverviewTopRowCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OverviewTopRowCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OverviewTopRowCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BMECont = lv_obj_create(ui_OverviewTopRowCont);
    lv_obj_set_width(ui_BMECont, lv_pct(22));
    lv_obj_set_height(ui_BMECont, lv_pct(100));
    lv_obj_set_align(ui_BMECont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BMECont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BMECont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BMECont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_BMECont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BMECont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BMECont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BMECont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BMEHeaderCont = lv_obj_create(ui_BMECont);
    lv_obj_set_width(ui_BMEHeaderCont, lv_pct(100));
    lv_obj_set_height(ui_BMEHeaderCont, lv_pct(20));
    lv_obj_set_align(ui_BMEHeaderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BMEHeaderCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BMEHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BMEHeaderCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BMEHeaderLabel = lv_label_create(ui_BMEHeaderCont);
    lv_obj_set_width(ui_BMEHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BMEHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BMEHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BMEHeaderLabel, "Altimeter");

    ui_BMEInfoCont = lv_obj_create(ui_BMECont);
    lv_obj_set_width(ui_BMEInfoCont, lv_pct(100));
    lv_obj_set_height(ui_BMEInfoCont, lv_pct(80));
    lv_obj_set_align(ui_BMEInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BMEInfoCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BMEInfoCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BMEInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_BMEInfoCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BMEInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BMEInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BMEInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BMEInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeInfoCont = lv_obj_create(ui_BMEInfoCont);
    lv_obj_set_height(ui_AltitudeInfoCont, 50);
    lv_obj_set_width(ui_AltitudeInfoCont, lv_pct(100));
    lv_obj_set_align(ui_AltitudeInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AltitudeInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AltitudeInfoCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AltitudeInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AltitudeValueLabel = lv_label_create(ui_AltitudeInfoCont);
    lv_obj_set_width(ui_AltitudeValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeValueLabel, "10,000");
    lv_obj_set_style_text_color(ui_AltitudeValueLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AltitudeValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltitudeValueLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeUnitLabel = lv_label_create(ui_AltitudeInfoCont);
    lv_obj_set_width(ui_AltitudeUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeUnitLabel, "m");
    lv_obj_set_style_text_font(ui_AltitudeUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureInfoCont = lv_obj_create(ui_BMEInfoCont);
    lv_obj_set_height(ui_PressureInfoCont, 50);
    lv_obj_set_width(ui_PressureInfoCont, lv_pct(100));
    lv_obj_set_align(ui_PressureInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PressureInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PressureInfoCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PressureInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PressureValueLabel = lv_label_create(ui_PressureInfoCont);
    lv_obj_set_width(ui_PressureValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressureValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureValueLabel, "23,800");
    lv_obj_set_style_text_color(ui_PressureValueLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressureValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PressureValueLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureUnitLabel = lv_label_create(ui_PressureInfoCont);
    lv_obj_set_width(ui_PressureUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressureUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureUnitLabel, "Pa");
    lv_obj_set_style_text_font(ui_PressureUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempCont = lv_obj_create(ui_OverviewTopRowCont);
    lv_obj_set_width(ui_TempCont, lv_pct(24));
    lv_obj_set_height(ui_TempCont, lv_pct(100));
    lv_obj_set_align(ui_TempCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TempCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_TempCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempHeaderCont = lv_obj_create(ui_TempCont);
    lv_obj_set_width(ui_TempHeaderCont, lv_pct(100));
    lv_obj_set_height(ui_TempHeaderCont, lv_pct(20));
    lv_obj_set_align(ui_TempHeaderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempHeaderCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TempHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TempHeaderCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempHeaderLabel = lv_label_create(ui_TempHeaderCont);
    lv_obj_set_width(ui_TempHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempHeaderLabel, "Temperature");

    ui_TempInfoCont = lv_obj_create(ui_TempCont);
    lv_obj_set_width(ui_TempInfoCont, lv_pct(100));
    lv_obj_set_height(ui_TempInfoCont, lv_pct(80));
    lv_obj_set_align(ui_TempInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TempInfoCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_TempInfoCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempArc = lv_arc_create(ui_TempInfoCont);
    lv_obj_set_width(ui_TempArc, lv_pct(100));
    lv_obj_set_height(ui_TempArc, lv_pct(80));
    lv_obj_set_x(ui_TempArc, 20);
    lv_obj_set_y(ui_TempArc, -77);
    lv_obj_set_align(ui_TempArc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempArc, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TempArc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_value(ui_TempArc, 30);
    lv_obj_set_style_pad_left(ui_TempArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TempValueLabel = lv_label_create(ui_TempArc);
    lv_obj_set_width(ui_TempValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempValueLabel, "35");
    lv_obj_set_style_text_font(ui_TempValueLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempUnitLabel = lv_label_create(ui_TempArc);
    lv_obj_set_width(ui_TempUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempUnitLabel, " °C");
    lv_obj_set_style_text_font(ui_TempUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityCont = lv_obj_create(ui_OverviewTopRowCont);
    lv_obj_set_width(ui_HumidityCont, lv_pct(24));
    lv_obj_set_height(ui_HumidityCont, lv_pct(100));
    lv_obj_set_align(ui_HumidityCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HumidityCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HumidityCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumidityCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_HumidityCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HumidityCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HumidityCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HumidityCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityHeaderCont = lv_obj_create(ui_HumidityCont);
    lv_obj_set_width(ui_HumidityHeaderCont, lv_pct(100));
    lv_obj_set_height(ui_HumidityHeaderCont, lv_pct(20));
    lv_obj_set_align(ui_HumidityHeaderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumidityHeaderCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HumidityHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HumidityHeaderCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityHeaderLabel = lv_label_create(ui_HumidityHeaderCont);
    lv_obj_set_width(ui_HumidityHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidityHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityHeaderLabel, "Humidity");

    ui_HumidityInfoCont = lv_obj_create(ui_HumidityCont);
    lv_obj_set_width(ui_HumidityInfoCont, lv_pct(100));
    lv_obj_set_height(ui_HumidityInfoCont, lv_pct(80));
    lv_obj_set_align(ui_HumidityInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HumidityInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HumidityInfoCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumidityInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_HumidityInfoCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HumidityInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HumidityInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HumidityInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HumidityInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidtyArc = lv_arc_create(ui_HumidityInfoCont);
    lv_obj_set_width(ui_HumidtyArc, lv_pct(100));
    lv_obj_set_height(ui_HumidtyArc, lv_pct(80));
    lv_obj_set_x(ui_HumidtyArc, 20);
    lv_obj_set_y(ui_HumidtyArc, -77);
    lv_obj_set_align(ui_HumidtyArc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HumidtyArc, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HumidtyArc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_value(ui_HumidtyArc, 80);
    lv_obj_set_style_pad_left(ui_HumidtyArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HumidtyArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HumidtyArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HumidtyArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_HumidtyArc, lv_color_hex(0xF81B36), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_HumidtyArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_HumidtyArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HumidtyArc, lv_color_hex(0xF81B36), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidtyArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HumidityValueLabel = lv_label_create(ui_HumidtyArc);
    lv_obj_set_width(ui_HumidityValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidityValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityValueLabel, "80");
    lv_obj_set_style_text_font(ui_HumidityValueLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityUnitLabel = lv_label_create(ui_HumidtyArc);
    lv_obj_set_width(ui_HumidityUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidityUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityUnitLabel, "%");
    lv_obj_set_style_text_font(ui_HumidityUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagnetometerCont = lv_obj_create(ui_OverviewTopRowCont);
    lv_obj_set_width(ui_MagnetometerCont, lv_pct(24));
    lv_obj_set_height(ui_MagnetometerCont, lv_pct(100));
    lv_obj_set_align(ui_MagnetometerCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MagnetometerCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MagnetometerCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MagnetometerCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_MagnetometerCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MagnetometerCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MagnetometerCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MagnetometerCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagentometerHeaderCont = lv_obj_create(ui_MagnetometerCont);
    lv_obj_set_width(ui_MagentometerHeaderCont, lv_pct(100));
    lv_obj_set_height(ui_MagentometerHeaderCont, lv_pct(20));
    lv_obj_set_align(ui_MagentometerHeaderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MagentometerHeaderCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MagentometerHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MagentometerHeaderCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagnetometerHeaderLabel = lv_label_create(ui_MagentometerHeaderCont);
    lv_obj_set_width(ui_MagnetometerHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagnetometerHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MagnetometerHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagnetometerHeaderLabel, "Magnetometer");

    ui_MagentometerInfoCont = lv_obj_create(ui_MagnetometerCont);
    lv_obj_set_width(ui_MagentometerInfoCont, lv_pct(100));
    lv_obj_set_height(ui_MagentometerInfoCont, lv_pct(80));
    lv_obj_set_align(ui_MagentometerInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MagentometerInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MagentometerInfoCont, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MagentometerInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_MagentometerInfoCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MagentometerInfoCont, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MagentometerInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MagentometerInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MagentometerInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagentometerArc = lv_arc_create(ui_MagentometerInfoCont);
    lv_obj_set_width(ui_MagentometerArc, lv_pct(100));
    lv_obj_set_height(ui_MagentometerArc, lv_pct(80));
    lv_obj_set_x(ui_MagentometerArc, 20);
    lv_obj_set_y(ui_MagentometerArc, -77);
    lv_obj_set_align(ui_MagentometerArc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MagentometerArc, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MagentometerArc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_range(ui_MagentometerArc, 0, 360);
    lv_arc_set_value(ui_MagentometerArc, 180);
    lv_arc_set_mode(ui_MagentometerArc, LV_ARC_MODE_REVERSE);

    lv_obj_set_style_arc_color(ui_MagentometerArc, lv_color_hex(0x04B25F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MagentometerArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MagentometerArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MagentometerArc, lv_color_hex(0x04B25F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MagentometerArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MagnetometerValueLabel = lv_label_create(ui_MagentometerArc);
    lv_obj_set_width(ui_MagnetometerValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagnetometerValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MagnetometerValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagnetometerValueLabel, "80");
    lv_obj_set_style_text_font(ui_MagnetometerValueLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MagentometerUnitLabel = lv_label_create(ui_MagentometerArc);
    lv_obj_set_width(ui_MagentometerUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MagentometerUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MagentometerUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MagentometerUnitLabel, "%");
    lv_obj_set_style_text_font(ui_MagentometerUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OverviewBottomRowCont = lv_obj_create(ui_OverviewTab);
    lv_obj_set_width(ui_OverviewBottomRowCont, lv_pct(100));
    lv_obj_set_height(ui_OverviewBottomRowCont, lv_pct(49));
    lv_obj_set_x(ui_OverviewBottomRowCont, 0);
    lv_obj_set_y(ui_OverviewBottomRowCont, -12);
    lv_obj_set_align(ui_OverviewBottomRowCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_OverviewBottomRowCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_OverviewBottomRowCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_OverviewBottomRowCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_OverviewBottomRowCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OverviewBottomRowCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OverviewBottomRowCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OverviewBottomRowCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OverviewBottomRowCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoubleDataCont = lv_obj_create(ui_OverviewBottomRowCont);
    lv_obj_set_width(ui_DoubleDataCont, lv_pct(25));
    lv_obj_set_height(ui_DoubleDataCont, lv_pct(100));
    lv_obj_set_align(ui_DoubleDataCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DoubleDataCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DoubleDataCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DoubleDataCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_DoubleDataCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DoubleDataCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DoubleDataCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DoubleDataCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPSCont = lv_obj_create(ui_DoubleDataCont);
    lv_obj_set_width(ui_GPSCont, lv_pct(100));
    lv_obj_set_height(ui_GPSCont, lv_pct(60));
    lv_obj_set_align(ui_GPSCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_GPSCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_GPSCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GPSCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_GPSCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_GPSCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GPSCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GPSCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GPSCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPSHeaderCont = lv_obj_create(ui_GPSCont);
    lv_obj_set_width(ui_GPSHeaderCont, lv_pct(100));
    lv_obj_set_height(ui_GPSHeaderCont, lv_pct(10));
    lv_obj_set_align(ui_GPSHeaderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GPSHeaderCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GPSHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GPSHeaderCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_GPSHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GPSHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GPSHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GPSHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPSHeaderLabel = lv_label_create(ui_GPSHeaderCont);
    lv_obj_set_width(ui_GPSHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPSHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GPSHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPSHeaderLabel, "GPS");

    ui_GPSInfoCont = lv_obj_create(ui_GPSCont);
    lv_obj_set_width(ui_GPSInfoCont, lv_pct(100));
    lv_obj_set_height(ui_GPSInfoCont, lv_pct(75));
    lv_obj_set_align(ui_GPSInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_GPSInfoCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_GPSInfoCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GPSInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_GPSInfoCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_GPSInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GPSInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GPSInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GPSInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LatInfoCont = lv_obj_create(ui_GPSInfoCont);
    lv_obj_set_width(ui_LatInfoCont, lv_pct(100));
    lv_obj_set_height(ui_LatInfoCont, lv_pct(40));
    lv_obj_set_align(ui_LatInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LatInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LatInfoCont, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LatInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LatitudeValueLabel = lv_label_create(ui_LatInfoCont);
    lv_obj_set_width(ui_LatitudeValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LatitudeValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LatitudeValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LatitudeValueLabel, "37.765");
    lv_obj_set_style_text_color(ui_LatitudeValueLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LatitudeValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LatitudeValueLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LatitudeUnitLabel = lv_label_create(ui_LatInfoCont);
    lv_obj_set_width(ui_LatitudeUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LatitudeUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LatitudeUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LatitudeUnitLabel, "lat");
    lv_obj_set_style_text_font(ui_LatitudeUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LongInfoCont = lv_obj_create(ui_GPSInfoCont);
    lv_obj_set_width(ui_LongInfoCont, lv_pct(100));
    lv_obj_set_height(ui_LongInfoCont, lv_pct(40));
    lv_obj_set_align(ui_LongInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LongInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LongInfoCont, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LongInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LongValueLabel = lv_label_create(ui_LongInfoCont);
    lv_obj_set_width(ui_LongValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LongValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LongValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LongValueLabel, "-122.5675");
    lv_obj_set_style_text_color(ui_LongValueLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LongValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LongValueLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LongUnitLabel = lv_label_create(ui_LongInfoCont);
    lv_obj_set_width(ui_LongUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LongUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LongUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LongUnitLabel, "lon");
    lv_obj_set_style_text_font(ui_LongUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UVCont = lv_obj_create(ui_DoubleDataCont);
    lv_obj_set_width(ui_UVCont, lv_pct(100));
    lv_obj_set_height(ui_UVCont, lv_pct(60));
    lv_obj_set_align(ui_UVCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_UVCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_UVCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_UVCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_UVCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_UVCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_UVCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_UVCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_UVCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UVHeaderCont = lv_obj_create(ui_UVCont);
    lv_obj_set_width(ui_UVHeaderCont, lv_pct(100));
    lv_obj_set_height(ui_UVHeaderCont, lv_pct(10));
    lv_obj_set_align(ui_UVHeaderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_UVHeaderCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_UVHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_UVHeaderCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_UVHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_UVHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_UVHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_UVHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UVHeaderLabel = lv_label_create(ui_UVHeaderCont);
    lv_obj_set_width(ui_UVHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UVHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UVHeaderLabel, "UV");

    ui_UVInfoCont = lv_obj_create(ui_UVCont);
    lv_obj_set_width(ui_UVInfoCont, lv_pct(100));
    lv_obj_set_height(ui_UVInfoCont, lv_pct(80));
    lv_obj_set_align(ui_UVInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_UVInfoCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_UVInfoCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_UVInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_UVInfoCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_UVInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_UVInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_UVInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_UVInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LatInfoCont1 = lv_obj_create(ui_UVInfoCont);
    lv_obj_set_width(ui_LatInfoCont1, lv_pct(100));
    lv_obj_set_height(ui_LatInfoCont1, lv_pct(40));
    lv_obj_set_align(ui_LatInfoCont1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LatInfoCont1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LatInfoCont1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LatInfoCont1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UVValueLabel = lv_label_create(ui_LatInfoCont1);
    lv_obj_set_width(ui_UVValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UVValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UVValueLabel, "100");
    lv_obj_set_style_text_color(ui_UVValueLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UVValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UVValueLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UVUnitLabel = lv_label_create(ui_LatInfoCont1);
    lv_obj_set_width(ui_UVUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UVUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UVUnitLabel, "lux");
    lv_obj_set_style_text_font(ui_UVUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageCont = lv_obj_create(ui_OverviewBottomRowCont);
    lv_obj_set_width(ui_VoltageCont, lv_pct(24));
    lv_obj_set_height(ui_VoltageCont, lv_pct(100));
    lv_obj_set_align(ui_VoltageCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VoltageCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_VoltageCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VoltageCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_VoltageCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VoltageCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VoltageCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VoltageCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageHeaderCont = lv_obj_create(ui_VoltageCont);
    lv_obj_set_width(ui_VoltageHeaderCont, lv_pct(100));
    lv_obj_set_height(ui_VoltageHeaderCont, lv_pct(20));
    lv_obj_set_align(ui_VoltageHeaderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VoltageHeaderCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VoltageHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_VoltageHeaderCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageHeaderLabel = lv_label_create(ui_VoltageHeaderCont);
    lv_obj_set_width(ui_VoltageHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VoltageHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltageHeaderLabel, "Voltage");

    ui_VoltageInfoCont = lv_obj_create(ui_VoltageCont);
    lv_obj_set_width(ui_VoltageInfoCont, lv_pct(100));
    lv_obj_set_height(ui_VoltageInfoCont, lv_pct(80));
    lv_obj_set_align(ui_VoltageInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VoltageInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VoltageInfoCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VoltageInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_VoltageInfoCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VoltageInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VoltageInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VoltageInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VoltageInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageArc = lv_arc_create(ui_VoltageInfoCont);
    lv_obj_set_width(ui_VoltageArc, lv_pct(100));
    lv_obj_set_height(ui_VoltageArc, lv_pct(80));
    lv_obj_set_x(ui_VoltageArc, 20);
    lv_obj_set_y(ui_VoltageArc, -77);
    lv_obj_set_align(ui_VoltageArc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VoltageArc, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VoltageArc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_range(ui_VoltageArc, 0, 5);
    lv_arc_set_value(ui_VoltageArc, 5);
    lv_obj_set_style_pad_left(ui_VoltageArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VoltageArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VoltageArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VoltageArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_VoltageArc, lv_color_hex(0x04B25F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_VoltageArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VoltageArc, lv_color_hex(0x04B25F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoltageArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VoltageArc, lv_color_hex(0x04B25F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoltageArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_VoltageValueLabel = lv_label_create(ui_VoltageArc);
    lv_obj_set_width(ui_VoltageValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VoltageValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltageValueLabel, "5.0");
    lv_obj_set_style_text_font(ui_VoltageValueLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageUnitLabel = lv_label_create(ui_VoltageArc);
    lv_obj_set_width(ui_VoltageUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VoltageUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltageUnitLabel, "V");
    lv_obj_set_style_text_font(ui_VoltageUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentCont = lv_obj_create(ui_OverviewBottomRowCont);
    lv_obj_set_width(ui_CurrentCont, lv_pct(24));
    lv_obj_set_height(ui_CurrentCont, lv_pct(100));
    lv_obj_set_align(ui_CurrentCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CurrentCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CurrentCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CurrentCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_CurrentCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrentCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrentCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrentCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentHeaderCont = lv_obj_create(ui_CurrentCont);
    lv_obj_set_width(ui_CurrentHeaderCont, lv_pct(100));
    lv_obj_set_height(ui_CurrentHeaderCont, lv_pct(20));
    lv_obj_set_align(ui_CurrentHeaderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CurrentHeaderCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CurrentHeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_CurrentHeaderCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentHeaderLabel = lv_label_create(ui_CurrentHeaderCont);
    lv_obj_set_width(ui_CurrentHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CurrentHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentHeaderLabel, "Current");

    ui_CurrentInfoCont = lv_obj_create(ui_CurrentCont);
    lv_obj_set_width(ui_CurrentInfoCont, lv_pct(100));
    lv_obj_set_height(ui_CurrentInfoCont, lv_pct(80));
    lv_obj_set_align(ui_CurrentInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CurrentInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CurrentInfoCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CurrentInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_CurrentInfoCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CurrentInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrentInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrentInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrentInfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentArc = lv_arc_create(ui_CurrentInfoCont);
    lv_obj_set_width(ui_CurrentArc, lv_pct(100));
    lv_obj_set_height(ui_CurrentArc, lv_pct(80));
    lv_obj_set_x(ui_CurrentArc, 20);
    lv_obj_set_y(ui_CurrentArc, -77);
    lv_obj_set_align(ui_CurrentArc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CurrentArc, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CurrentArc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_range(ui_CurrentArc, 0, 5);
    lv_arc_set_value(ui_CurrentArc, 3);
    lv_obj_set_style_pad_left(ui_CurrentArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrentArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrentArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrentArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_CurrentValueLabel = lv_label_create(ui_CurrentArc);
    lv_obj_set_width(ui_CurrentValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CurrentValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentValueLabel, "5.0");
    lv_obj_set_style_text_font(ui_CurrentValueLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentUnitLabel = lv_label_create(ui_CurrentArc);
    lv_obj_set_width(ui_CurrentUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CurrentUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentUnitLabel, "A");
    lv_obj_set_style_text_font(ui_CurrentUnitLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPU6050Cont = lv_obj_create(ui_OverviewBottomRowCont);
    lv_obj_set_width(ui_MPU6050Cont, lv_pct(22));
    lv_obj_set_height(ui_MPU6050Cont, lv_pct(100));
    lv_obj_set_align(ui_MPU6050Cont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MPU6050Cont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MPU6050Cont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MPU6050Cont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_MPU6050Cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MPU6050Cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MPU6050Cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MPU6050Cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPU605HeaderCont = lv_obj_create(ui_MPU6050Cont);
    lv_obj_set_width(ui_MPU605HeaderCont, lv_pct(100));
    lv_obj_set_height(ui_MPU605HeaderCont, lv_pct(20));
    lv_obj_set_align(ui_MPU605HeaderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MPU605HeaderCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MPU605HeaderCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MPU605HeaderCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Attitude = lv_label_create(ui_MPU605HeaderCont);
    lv_obj_set_width(ui_Attitude, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Attitude, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Attitude, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Attitude, "Altimeter");

    ui_MPU6050InfoCont = lv_obj_create(ui_MPU6050Cont);
    lv_obj_set_width(ui_MPU6050InfoCont, lv_pct(100));
    lv_obj_set_height(ui_MPU6050InfoCont, lv_pct(80));
    lv_obj_set_align(ui_MPU6050InfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MPU6050InfoCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MPU6050InfoCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MPU6050InfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_MPU6050InfoCont, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MPU6050InfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MPU6050InfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MPU6050InfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MPU6050InfoCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccInfoCont = lv_obj_create(ui_MPU6050InfoCont);
    lv_obj_set_width(ui_AccInfoCont, lv_pct(100));
    lv_obj_set_height(ui_AccInfoCont, lv_pct(45));
    lv_obj_set_align(ui_AccInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AccInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AccInfoCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AccInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AltitudeValueLabel1 = lv_label_create(ui_AccInfoCont);
    lv_obj_set_width(ui_AltitudeValueLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeValueLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeValueLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeValueLabel1, "10,000");
    lv_obj_set_style_text_color(ui_AltitudeValueLabel1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AltitudeValueLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltitudeValueLabel1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeUnitLabel1 = lv_label_create(ui_AccInfoCont);
    lv_obj_set_width(ui_AltitudeUnitLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeUnitLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeUnitLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeUnitLabel1, "m");
    lv_obj_set_style_text_font(ui_AltitudeUnitLabel1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GyroInfoCont = lv_obj_create(ui_MPU6050InfoCont);
    lv_obj_set_width(ui_GyroInfoCont, lv_pct(100));
    lv_obj_set_height(ui_GyroInfoCont, lv_pct(45));
    lv_obj_set_align(ui_GyroInfoCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_GyroInfoCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_GyroInfoCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GyroInfoCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PressureValueLabel1 = lv_label_create(ui_GyroInfoCont);
    lv_obj_set_width(ui_PressureValueLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureValueLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressureValueLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureValueLabel1, "23,800");
    lv_obj_set_style_text_color(ui_PressureValueLabel1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressureValueLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PressureValueLabel1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureUnitLabel1 = lv_label_create(ui_GyroInfoCont);
    lv_obj_set_width(ui_PressureUnitLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureUnitLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressureUnitLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureUnitLabel1, "Pa");
    lv_obj_set_style_text_font(ui_PressureUnitLabel1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SerialSelector = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_options(ui_SerialSelector, "ttyUSB0\nttyUSB1\nttyUSB2\nttyUSB3\nttyUSB4\nttyUSB5");
    lv_obj_set_width(ui_SerialSelector, 150);
    lv_obj_set_height(ui_SerialSelector, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SerialSelector, -299);
    lv_obj_set_y(ui_SerialSelector, -33);
    lv_obj_set_align(ui_SerialSelector, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SerialSelector, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



}
